version: "3.9"

services:
  mais-envios-backend:
    container_name: mais-envios-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./code:/app
    environment:
      NODE_ENV: development
      API_PORT: 3000
      API_NAME: "MS-ME-Etiqueta-DEV"
      SWAGGER_ENABLED: "true"
      SWAGGER_PATH: "swagger-docs"
      SIZE_MAX_FILE_BYTES: "5242880"
